source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '3.2.21'

gem 'pg'
gem 'pg_power'
gem 'activerecord-postgres-springest', git: 'https://github.com/Springest/activerecord-postgres-springest.git'

gem 'logstasher'                                  # Logstash compatible logs

gem 'dalli'                                       # Memcache for cache
gem 'redis'                                       # talk to Redis
gem 'redis-session-store'
gem 'connection_pool'                             # generic connection pool; used for redis

gem 'devise', '~> 2.2'                            # Authentication
gem 'omniauth'                                    # Authenticate with FB, Twitter, etc
gem 'omniauth-linkedin'
gem 'omniauth-saml'
gem 'linkedin'

gem 'google-qr'                                   # Generate url strings and HTML img tags for QR codes from Google's QR code infographics API

gem 'ancestry'                                    # tree structure (for example: menu)

gem 'sprockets'                                   # asset compilation
gem 'turbo-sprockets-rails3'                      # faster asset compilation

gem 'addressable'                                 # smart URI parsing

# Assets
gem 'coffee-rails', '~> 3.2.1'                    # Coffeescript
gem 'uglifier'                                    # compressor
gem 'asset_sync'

gem 'rack-contrib'                                # IP filtering with Rack::Access
gem 'sass-rails', '~> 3.2.3'                      # Sass
gem 'neat', '~> 1.2.1'                            # Sass Responsive framework
gem 'font-awesome-rails', '~> 4.3.0.0'            # Fontawesome - iconic font
gem 'jquery-rails'                                # jQuery and Rails work well together
gem 'jquery-ui-rails'                             # jQuery UI assets
gem 'ui_datepicker-rails3', "~> 1.1.1"            # override default datepicker
gem 'tinymce-rails', "~> 3.5.8"                   # TinyMCE WYSIWYG editor assets
gem 'tinymce-rails-langs'                         # TinyMCE language packs
gem 'jquery-tokeninput-rails'                     # Facebook like token input
gem 'slim-rails'                                  # Haml for views
gem 'redcarpet'
gem 'ace-rails-ap'                                # advanced editor
gem 'jquery-fileupload-rails'                     # jQuery file upload
gem 'carrierwave'                                 # file/image uploading (auth_url Rackspace from git)
gem 'mini_magick', '~> 3.6'                       # image manipulation (thumbnail/resize)
gem 'nokogiri_truncate_html'                      # truncate_html helper
gem 'mixpanel'                                    # Mixpanel event_tracker
gem 'mixpannenkoek'                               # Fluent query interface to the mixpanel gem
gem "ab_panel", "~> 0.3.1"                        # A/B testing with Mixpanel

gem 'simple_form', '~> 2.1.0'                     # simple generation of forms
gem 'grouped_validations'                         # group validations for tabs
gem 'client_side_validations'                     # validation
gem 'client_side_validations-simple_form'         # validation for simple forms

gem 'rails-i18n', '~> 3.0.0'                      # extra translations
gem 'iso-639'                                     # ISO-639 country codes
gem 'countries'                                   # adds countries

gem 'nokogiri'                                    # for parsing HTML text
gem 'htmlentities'                                # for parsing HTML text
gem 'tidy_ffi', require: false                    # tidy HTML text
gem 'feedjira'

gem 'sendgrid'                                    # use SendGrid easily
gem 'RedCloth'                                    # Markdown processor (for email templates)
gem 'liquid'                                      # variable substitution (for email templates)
gem 'premailer-rails'                             # convert HTML + CSS to a format that works with most email clients.

gem 'cancancan', '~> 1.9'                         # authorization
gem 'inherited_resources'                         # crud resources
gem 'kaminari'                                    # page results
gem 'jbuilder'                                    # JSON views
gem 'jpbuilder'                                   # JSONP views
gem 'validates_email_format_of'                   # email
gem 'js-routes'                                   # url helpers available in JavaScript

gem 'geocoder'                                    # used for region distance calculation
gem 'timezone'                                    # get time zone from location
gem 'andand'                                      # easy syntax for possible nulls

gem 'fog', '>=1.22.0'                             # cloud service integration

gem 'distribution'                                # for confidence intervals on review ratings
gem 'statistics2'

gem 'gibbon'                                      # Mailchimp api
gem 'survey-gizmo-ruby'                           # SurveyGizmo api

gem 'unicorn'                                     # the webserver
gem 'unicorn-worker-killer'                       # Keep Unicorn workers in shape: https://github.com/kzk/unicorn-worker-killer
gem 'gctools'                                     # Ruby 2.1+ compatible GC Tools for Unicorn
gem 'rack-timeout'                                # Rack timeout with a stacktrace.
gem 'capistrano'                                  # deployment framework
gem 'net-scp'
gem 'sidekiq'                                     # delayed jobs
gem 'sinatra'                                     # for the Sidekiq Web UI
gem 'appsignal', '0.11.8.beta.1'                  # Monitoring with AppSignal
gem 'grape-appsignal'                             # AppSignal support for Grape API

gem 'sunspot_rails'                               # Sunspot is a library for interaction with Solr
gem 'sunspot',       :git => 'https://github.com/Springest/sunspot.git', :tag => 'v2.1.0'  # Solr package for use with Sunspot
gem 'sunspot_solr',  :git => 'https://github.com/Springest/sunspot.git', :tag => 'v2.1.0'  # Solr package for use with Sunspot
gem 'ruby-progressbar'                            # progress bar for Solr indexing
gem 'term-extract'                                # Used to find trainings that are related to a deleted training.

gem 'active_attr'                                 # What ActiveModel left out (for use with non AR models)

gem 'grape', '~> 0.9.0'                           # REST-like API micro-framework for Ruby

gem 'multi_fetch_fragments'                       # Speed up cache fetches

group :development, :staging do
  if ENV['BETTER_ERRORS']
    gem 'better_errors'
  end
  if ENV['RACK_MINI_PROFILER']
    gem 'rack-mini-profiler'                      # Profile request inline
  end
  gem 'mailcatcher'                               # bundle exec mailcatcher (and open http://localhost:1080)
end

group :development, :test do
  gem 'parallel_tests'
  gem 'rubocop'
  gem 'jasmine'                                   # Unit testing JavaScript
  gem 'guard-jasmine'                             # Jasmine in Guard
end

group :development do
  gem "spring"                                    # Rails preloading with Spring
  gem "spring-commands-rspec"                     # Spring command for Rspec
  gem 'bumbler', require: false                   # track slowest loading gems.
  gem 'nokogiri-diff'                             # compare 2 HTML/XML docs
  gem 'request-log-analyzer'                      # Log parser
  gem 'oink'                                      # Parsable logs
  gem 'rb-fsevent'                                # used for guard, watches files changes
  gem 'rb-inotify', '~> 0.9', require: false      # used for guard, watches files changes
  gem 'thin'                                      # current WEBrick gives a load of warnings, so use thin instead
  gem 'byebug'
  gem 'pry-byebug'
  gem 'binding_of_caller'
  gem 'guard'                                     # autotesting
  gem 'guard-rspec'                               # Guard and RSpec work well together
  gem 'terminal-notifier-guard'                   # native OS X 10.8 notifications from tests
  gem 'launchy'                                   # shows page being tested in acceptance tests
  gem 'foreman'                                   # Run the whole app
  gem 'quiet_assets'                              # Silence Sprockets/assets noise in development log
end

group :test do
  gem 'rspec-instafail'
  gem 'factory_girl_rails'                        # use factories instead of fixtures
  gem 'faker'                                     # easily create fake data for tests
  gem 'rspec-rails', '~> 2.14.2'                  # test framework
  gem 'capybara', '~> 2.1.0'                      # an integration testing tool for Rack based web applications
  gem 'capybara-screenshot'                       # take screenshots if something fails
  gem "poltergeist", "~> 1.6.0"                   # for JS testing, could be used for screenshots as well
  gem 'database_cleaner'                          # manage DB between tests
  gem 'sunspot_matchers'                          # Rspec matchers for Sunspot Solr
  gem 'shoulda-matchers'                          # one-liners that test common Rails functionality
  gem 'sunspot-rails-tester', git: 'https://github.com/Springest/sunspot-rails-tester.git' # Rspec testing for Sunspot Solr
  gem 'timecop'                                   # freeze or travel through time
  gem 'webmock'                                   # mocks http requests, needed by VCR
  gem 'vcr'                                       # Fixtures for HTTP requests
  gem 'json_spec'                                 # test JSON results in specs
  gem 'jsonpath'                                  # process JSON with XPath like queries
  gem "fakeredis", :require => "fakeredis/rspec"  # Fake Redis
end

group :production, :staging do
  gem 'therubyracer', '~> 0.12.1'                 # JS compilation
  gem 'rails_12factor'                            # 12factor Rails pls
end

gem 'newrelic_rpm',   '~> 3.9.0'                # monitoring production env and deploys
gem 'newrelic-grape', '>= 2.0.0'                # NewRelic instrumentation for the Grape API DSL

gem 'ransack'                                     # advanced search form support

gem 'cloudservers'                                # Holds Rackspace API logic

gem 'whenever', :require => false                 # Crontabs via Capistrano

gem 'pipeline_dealers', git: 'https://github.com/Springest/pipeline_dealers.git'

gem 'builder'                                     # Pretty ez XML
gem 'rack-throttle'

gem 'rack-maintenance'                            # Serves a maintenance page use cap production maintenance:on
                                                  # to enable.
gem 'draper', '~> 1.0'                            # for decorator pattern
gem 'acts_as_list'                                # for sorting of lists

gem 'paper_trail', '~> 3.0.0'                     # papertrail / versioning

gem 'httparty'                                    # Makes HTTP fun again!
gem "cocoon"                                      # Makes nested forms awesome.

gem 'intercom', '~> 2.2.4'                        # For Intercom API requests
gem 'sidekiq-throttler'                           # throttle Sidekiq job execution, especially handy for interacting with rate limited APIs

gem 'oauth2'                                      # For MoneyBird API authentication
gem 'mail_view'                                   # Live preview of our disk-based e-mails

gem 'rack-utf8_sanitizer'

gem 'rails-backbone', git: 'https://github.com/codebrew/backbone-rails', tag: 'v1.1.2' # For using Backbone.js
