name: Docker builds to Quay.io

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./build/Dockerfile
          tags: quay.io/springest/build:${{ github.event.release.tag_name }}
      -
        name: Build and push ruby container
        id: docker_ruby
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./ruby/Dockerfile
          tags: quay.io/springest/build:${{ github.event.release.tag_name }}
      -
        name: Image Digest
        run: |
          echo $${{ steps.docker_build.outputs.digest }}
          echo $${{ steps.docker_ruby.outputs.digest }}
